import React from 'react'
import Category from '../../components/category'
import Arrow from '../arrow'
import ScrollToTopOnMount from '../../../components/scrollToTopOnMount'

const LOL = () => {
  return (<React.Fragment>
    <ScrollToTopOnMount/>
    <Arrow/>
    <div style={{ marginTop: '40px', backgroundColor: '#202020' }}>
      <Category>League of Legends</Category>
    </div>
    <div className="a-tournament-buttons">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id sollicitudin urna. Nulla hendrerit, sem at pellentesque cursus, metus tortor ornare nulla, vitae tempor leo quam ac eros. Maecenas sed ultricies nulla, nec auctor odio. Mauris gravida turpis quis velit congue, eget ultrices justo tempor. Ut vitae nulla sit amet elit viverra dictum et a justo. Sed semper viverra nibh, sed suscipit lacus suscipit sit amet. Nullam nec quam eros.</p>
    </div>
  </React.Fragment>)
}


export default LOL
